module.exports = {
    "extends": "eslint:recommended",
    "rules": {
        "semi": [2, "always"],
        "semi-spacing": [1],
        "semi-style": [2],
        "quotes": [1, "single", { "avoidEscape": true }],
        "quote-props": [1, "as-needed"],
        "camelcase": [1, { "ignoreDestructuring": true }],
        "comma-dangle": [1, "always-multiline"],
        "no-multi-spaces": [1, { "ignoreEOLComments": true }],
        "eol-last": [1],
        "new-parens": [1],
        "no-multiple-empty-lines": [1],
        "no-negated-condition": [1],
        "no-trailing-spaces": [1],
        "space-in-parens": [1],
        "space-infix-ops": [2],
        "space-unary-ops": [2, { "words": true, "nonwords": false }],
        "switch-colon-spacing": [1],
        "template-tag-spacing": [1],
        "generator-star-spacing": [1],
        "no-duplicate-imports": [1],
        "no-useless-computed-key": [1],
        "no-useless-constructor": [2],
        "no-useless-rename": [1],
        "no-var": [1],
        "object-shorthand": [1],
        "prefer-arrow-callback": [1],
        "prefer-const": [1],
        "prefer-destructuring": [1],
        "prefer-rest-params": [1],
        "prefer-spread": [1],
        "prefer-template": [1],
        "rest-spread-spacing": [1, "never"],
        "template-curly-spacing": [1, "always"],
        "yield-star-spacing": [1],

        "array-bracket-newline": [1, "consistent"],
        "array-element-newline": [1, "consistent"],
        "array-bracket-spacing": [1, "never"],
        "computed-property-spacing": [1],

        "block-spacing": [1, "always"],
        "space-before-blocks": [1, "always"],
        "brace-style": [1, "1tbs", { "allowSingleLine": true }],
        "key-spacing": [1, { 
            "singleLine": { "mode": "strict" },
            "multiLine": { "mode": "minimum" }, 
        }],
        "object-curly-newline": [1, { "multiline": true }],
        "object-curly-spacing": [1, "always"],
        "keyword-spacing": [1],
        "linebreak-style": [1, "windows"],

        "space-before-function-paren": [1, "never"],
        "func-call-spacing": [1, "never"],
        "func-name-matching": [2],
        "function-paren-newline": [1, "consistent"],
        "implicit-arrow-linebreak": [1, "beside"],
        "indent": [1, 4, { "SwitchCase": 1 }],

        "arrow-body-style": [1, "as-needed"],
        "arrow-parens": [1, "as-needed"],
        "arrow-spacing": [1],

        "comma-spacing": [1],
        "comma-style": [1],
        "dot-location": [1, "property"],
        "dot-notation": [1],
        "newline-per-chained-call": [1, { "ignoreChainWithDepth": 2 }],

        "no-async-promise-executor": [1],
        "no-await-in-loop": [1],
        "no-console": [0],
        "curly": [1, "multi-line", "consistent"],
        "nonblock-statement-body-position": [1, "beside"],
        "eqeqeq": [2, "always"],
        "guard-for-in": [2],
        "no-div-regex": [1],
        "no-else-return": [2],
        "no-eq-null": [2],
        "no-extend-native": [2],
        "no-extra-bind": [1],
        "no-extra-label": [1],
        "no-implicit-coercion": [1],
        "no-loop-func": [1],
        "no-new": [1],
        "no-octal-escape": [2],
        "no-proto": [2],
        "no-return-assign": [2],
        "no-return-await": [1],
        "no-self-compare": [1],
        "no-sequences": [1],
        "no-throw-literal": [2],
        "no-unused-expressions": [2, { "allowShortCircuit": true, "allowTernary": true }],
        "no-useless-call": [1],
        "no-useless-catch": [1],
        "no-useless-concat": [1],
        "no-useless-return": [1],
        "wrap-iife": [2, "inside", { "functionPrototypeMethods": true }],
        "yoda": [1, "never" , { "onlyEquality": true }],
        "no-label-var": [2],
        "no-shadow-restricted-names": [2],
        "no-use-before-define": [2],
        "no-array-constructor": [1],
        "no-multi-assign": [2],
        "no-unneeded-ternary": [1],
        "no-whitespace-before-property": [1],

        "no-buffer-constructor": [2],
        "no-mixed-requires": [1],
        "no-new-require": [2],
        "no-path-concat": [2],
        "no-new-object": [1],





        "no-compare-neg-zero": [2],
        "require-atomic-updates": [2],
        "array-callback-return": [2, { "allowImplicit": true }],
        "no-caller": [2],




    }
}